version: '3.7'
services:
  debug:
    image: centos:centos8
    container_name: debug-dev
    privileged: true
    tty: true
    networks: 
      dev_net:
        ipv4_address: '172.30.1.234'
    volumes:
      - ../../project:/root/code
      - /etc/localtime:/etc/localtime:ro

networks:
  dev_net:
    external: true