version: '3.7'

services: 
  rabbit:
    image: rabbitmq:3.8.15-rc.2-management-alpine
    container_name: rabbit-dev
    restart: always
    privileged: true
    networks: 
      dev_net:
        ipv4_address: 172.20.1.200
    ports: 
      - 5672:5672
      - 15672:15672
    environment: 
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=1111
    volumes: 
      - ./data:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime:ro

networks: 
  dev_net:
    external: true