version: '3.7'

services: 
  rabbit:
    image: rabbitmq:3.8.15-rc.2-management-alpine
    container_name: rabbit-dev
    restart: always
    privileged: true
    networks: 
      dev_net:
        ipv4_address: 172.20.0.30
    ports: 
      - 5672:5672
      - 15672:15672
    environment: 
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=1111
    # volumes: 
    #   - ./data:/var/lib/rabbitmq

networks: 
  dev_net:
    external: true
    