version: '3.7'
services:
  etcdkeeper:
    image: evildecay/etcdkeeper:latest
    container_name: dev_etcdkeeper
    privileged: true
    restart: always
    environment:
      HOST: 0.0.0.0
    networks:
      dev_net:
        ipv4_address: 172.20.1.11
    ports:
      - 8800:8080

networks:
  dev_net:
    external: true