version: '3.7'
services: 
  etcdkeeper:
    image: evildecay/etcdkeeper
    container_name: etcdkeeper-dev
    privileged: true
    restart: always
    networks: 
      dev_net:
        ipv4_address: 172.20.0.3
    ports: 
      - 8000:8080
    environment: 
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai

networks: 
  dev_net:
    external: true
