version: '3.7'
services:
  portainer:
    image: docker.io/portainer/portainer
    restart: always
    container_name: portainer-dev
    ports: 
      - "9000:9000"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock