version: '3.7'
services:
  portainer:
    image: portainer/portainer
    restart: always
    container_name: portainer-dev
    networks:
      dev_net:
        ipv4_address: '172.20.0.100'
    ports: 
      - "9000:9000"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro

networks:
  dev_net:
    external: true