version: '3.7'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-dev
    networks:
      dev_net:
        ipv4_address: 172.20.2.100
    ports:
      - 3306:3306
    restart: always
    privileged: true
    volumes:
      - ./db:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
      - ./logs:/var/log/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: iegad
      MYSQL_PASSWORD: 1111

networks:
  dev_net:
    external: true
