version: '3.7'
services:
  mongo:
    image: mongo
    container_name: mongo-dev
    restart: always
    networks:
      dev_net:
        ipv4_address: 172.20.3.100
    ports: 
      - 27017:27017
    privileged: true
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
      - ./mongod.conf:/etc/mongod.conf

networks:
  dev_net:
    external: true