version: '3.7'
services:
  redis:
    image: redis
    container_name: redis-dev
    command: redis-server /etc/redis.conf
    privileged: true
    restart: always
    networks:
      dev_net:
        ipv4_address: '172.30.1.5'
    ports:
      - 6379:6379
    volumes:
      - "./redis.conf:/etc/redis.conf"
      - "./data:/data"
      - /etc/localtime:/etc/localtime:ro

networks:
  dev_net:
    external: true